version: '3'
services:

  # The Application
#  app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    working_dir: /usr/app
#    volumes:
#      - ./:/usr/app
##    environment:
##      - "DB_PORT=3306"
##      - "DB_HOST=database"
#    ports:
#      - 8080:8080
#    links:
#      - database
##      - testdb

  # The Web Server
#  web:
#    build:
#      context: ./
#      dockerfile: web.dockerfile
#    working_dir: /var/www
#    volumes_from:
#      - app
#    ports:
#      - 8080:80

  # The Database

#  web:
#    build:
#      context: ./
#      dockerfile: wp.dockerfile
#    ports:
#      - 8080:80
#    environment:
#      WORDPRESS_DB_HOST: database
#      WORDPRESS_DB_USER: root
#      WORDPRESS_DB_PASSWORD: secret
#    ports:
#      - "8000:80"
#    depends_on:
#      - database




  database:
    image: mysql:5.7
    volumes:
      - db_nikahku:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

    restart: always



#  wordpress:
#    depends_on:
#      - database
#    image: wordpress:latest
#    ports:
#      - "8000:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: database
#      WORDPRESS_DB_USER: root
#      WORDPRESS_DB_PASSWORD: secret

  # The Database
#  testdb:
#    image: mysql:5.7
#    volumes:
#      - dbdata5:/var/lib/mysql
#    environment:
#      - "MYSQL_DATABASE=homestead"
#      - "MYSQL_USER=homestead"
#      - "MYSQL_PASSWORD=secret"
#      - "MYSQL_ROOT_PASSWORD=secret"
#    ports:
#        - "33070:3306"

volumes:
  db_nikahku: